# Generated by Django 3.0.5 on 2020-04-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200419_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='date_completed',
        ),
    ]
